<?php
/**
 * WooCommerce ABTest.
 * NOTE: DO NOT edit this file in WooCommerce core, this is generated from woocommerce-admin.
 */

namespace Automattic\WooCommerce\Admin\Features;

/**
 * Contains backend logic for the ABTest feature.
 */
class ABTest {
	/**
	 * Clear cache tool identifier.
	 */
	const OPTION_NAME = 'woocommerce_admin_abtests';

	/**
	 * Class instance.
	 *
	 * @var ABTest instance
	 */
	protected static $instance = null;

	/**
	 * Get class instance.
	 */
	public static function get_instance() {
		if ( ! self::$instance ) {
			self::$instance = new self();
		}
		return self::$instance;
	}

	/**
	 * Hook into WooCommerce.
	 */
	public function __construct() {
		add_filter( 'woocommerce_admin_preload_options', array( $this, 'preload_options' ) );
	}

	/**
	 * Preload abtest option.
	 *
	 * @param array $options Array of options to preload.
	 * @return array
	 */
	public function preload_options( $options ) {
		$options[] = self::OPTION_NAME;

		return $options;
	}
}
