<?php
/**
 * WooCommerce Onboarding Tasks
 * NOTE: DO NOT edit this file in WooCommerce core, this is generated from woocommerce-admin.
 *
 * @package Woocommerce Admin
 */

/**
 * Contains the logic for completing onboarding tasks.
 */
class WC_Admin_Onboarding_Tasks {
	/**
	 * Class instance.
	 *
	 * @var WC_Admin_Onboarding_Tasks instance
	 */
	protected static $instance = null;

	/**
	 * Name of the active task transient.
	 *
	 * @var string
	 */
	const ACTIVE_TASK_TRANSIENT = 'wc_onboarding_active_task';

	/**
	 * Get class instance.
	 */
	public static function get_instance() {
		if ( ! self::$instance ) {
			self::$instance = new self();
		}
		return self::$instance;
	}

	/**
	 * Constructor
	 */
	public function __construct() {
		add_action( 'admin_init', array( $this, 'set_active_task' ), 20 );
		add_action( 'admin_init', array( $this, 'check_active_task_completion' ), 1 );
	}


	/**
	 * Temporarily store the active task.
	 */
	public static function set_active_task() {
		if ( isset( $_GET[ self::ACTIVE_TASK_TRANSIENT ] ) ) { // WPCS: csrf ok.
			set_transient(
				self::ACTIVE_TASK_TRANSIENT,
				sanitize_title_with_dashes( wp_unslash( $_GET[ self::ACTIVE_TASK_TRANSIENT ] ) ),
				DAY_IN_SECONDS
			); // WPCS: csrf ok.
		}
	}

	/**
	 * Check for active task completion and redirect if complete.
	 */
	public static function check_active_task_completion() {
		$active_task = get_transient( self::ACTIVE_TASK_TRANSIENT );
		if ( ! $active_task ) {
			return;
		}

		switch ( $active_task ) {
			case 'products':
				$products = wp_count_posts( 'product' );
				if ( $products > 0 ) {
					self::redirect_to_dashboard();
				}
				break;
		}
	}

	/**
	 * Redirect to dashboard and delete active task transient.
	 */
	public static function redirect_to_dashboard() {
		delete_transient( self::ACTIVE_TASK_TRANSIENT );
		wp_safe_redirect( wc_admin_url() );
		exit;
	}
}

WC_Admin_Onboarding_Tasks::get_instance();
