<?php
/**
 * WooCommerce Onboarding
 * NOTE: DO NOT edit this file in WooCommerce core, this is generated from woocommerce-admin.
 */

namespace Automattic\WooCommerce\Admin\Internal\Onboarding;

/**
 * Initializes backend logic for the onboarding process.
 */
class Onboarding {
	/**
	 * Initialize onboarding functionality.
	 */
	public static function init() {
		OnboardingHelper::init();
		OnboardingIndustries::init();
		OnboardingJetpack::init();
		OnboardingMailchimp::init();
		OnboardingProfile::init();
		OnboardingSetupWizard::init();
		OnboardingSync::init();
		OnboardingThemes::init();
	}
}
