<?php
/**
 * WooCommerce Onboarding
 * NOTE: DO NOT edit this file in WooCommerce core, this is generated from woocommerce-admin.
 */

namespace Automattic\WooCommerce\Admin\Features\Onboarding;

use Automattic\WooCommerce\Admin\Features\OnboardingTasks\TaskLists;

/**
 * Initializes backend logic for the onboarding process.
 */
class Init {
	/**
	 * Initialize onboarding functionality.
	 */
	public function __construct() {
		OnboardingHelper::init();
		OnboardingIndustries::init();
		OnboardingJetpack::init();
		OnboardingMailchimp::init();
		OnboardingProducts::init();
		OnboardingSetupWizard::init();
		OnboardingSync::init();
		OnboardingThemes::init();
	}
}
