<?php
/**
 * WooCommerce Payment methods.
 * NOTE: DO NOT edit this file in WooCommerce core, this is generated from woocommerce-admin.
 */

namespace Automattic\WooCommerce\Admin;

/**
 * Contains backend logic for the Marketing feature.
 */
class PaymentPlugins {

	/**
	 * Name of recommended plugins transient.
	 *
	 * @var string
	 */
	const RECOMMENDED_PLUGINS_TRANSIENT = 'wc_recommended_payment_plugins';


	/**
	 * Class instance.
	 *
	 * @var PaymentPlugins instance
	 */
	protected static $instance = null;

	/**
	 * Get class instance.
	 */
	public static function get_instance() {
		if ( ! self::$instance ) {
			self::$instance = new self();
		}
		return self::$instance;
	}

	/**
	 * Load recommended payment plugins from WooCommerce.com
	 *
	 * @return array
	 */
	public function get_recommended_plugins() {
		$plugins = get_transient( self::RECOMMENDED_PLUGINS_TRANSIENT );

		if ( false === $plugins ) {
			include_once ABSPATH . '/wp-admin/includes/plugin-install.php';

			$url     = 'https://gist.githubusercontent.com/louwie17/f5c0a1c57d3a9ead78fcf385782d8a05/raw/e086d3dadf46c4a3c92bd0fe1dc27097563f5639/recommended-payments.json'; // 'https://127.0.0.1/wp-json/wccom/marketplace-suggestions/1.0/payment-suggestions.json';
			$request = wp_remote_get( $url );
			$plugins = [];

			if ( ! is_wp_error( $request ) && 200 === $request['response']['code'] ) {
				$plugins = json_decode( $request['body'], true );
			}
			foreach ( $plugins as $key => $plugin ) {
				$api = plugins_api(
					'plugin_information',
					array(
						'slug'   => $plugin['product'],
						'fields' => array(
							'sections'          => false,
							'short_description' => true,
							'icons'             => true,
						),
					)
				);
				if ( is_wp_error( $api ) ) {
					continue;
				}
				if ( ! array_key_exists( 'shortDescription', $plugins[ $key ] ) ) {
					$plugins[ $key ]['shortDescription'] = $api->short_description;
				}
			}

			set_transient(
				self::RECOMMENDED_PLUGINS_TRANSIENT,
				$plugins,
				// Expire transient in 15 minutes if remote get failed.
				// Cache an empty result to avoid repeated failed requests.
				empty( $plugins ) ? 900 : 3 * DAY_IN_SECONDS
			);
		}

		return array_values( $plugins );
	}
}

