name: 'Block Merge To main'
on: [ pull_request ]

jobs:
  block_merge:
    runs-on: ubuntu-latest
    steps:
    - name: Merge Blocked
      if: github.event.pull_request.base.ref == 'main'
      run: exit 1
