name: Publish docs
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2-beta
              with:
                  node-version: '14'

            - name: Install PNPM and install dependencies
              uses: pnpm/action-setup@v2.2.1
              with:
                version: ^6.24.2
                run_install: true

            - name: Build
              run: |
                  pnpm run build
                  pnpm run docs

            - name: Deploy docs
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_branch: gh-pages
                  publish_dir: ./docs
